[package]
name = "database_connection"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0",features = ["postgres"] }
dotenvy = "0.15"
chrono = "0.2.25"
